- src/model.py
Cleanup the following task running forever.
```
task: <Task pending name='Task-3' coro=<AsyncLLMEngine.run_engine_loop() running at /usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py:350> wait_for=<Future pending cb=[Task.task_wakeup()]>
```
> Terminate AsyncLLMEngine task gracefully

- ci/L0_backend_vllm/accuracy_test/accuracy_test.py
- ci/L0_backend_vllm/enabled_stream/enabled_stream_test.py
- ci/L0_backend_vllm/vllm_backend/vllm_backend_test.py
- samples/model_repository/vllm_model/config.pbtxt
- src/model.py
Moving default parameters from config to auto_complete function.
Also tests Python_backend's `set_model_transaction_policy`
> Adding autocomplete to vllm model.py

- README.md
Avoids a lot of confusion and improves user experience.
> Improve vLLM backend documentation

- ci/L0_backend_vllm/accuracy_test/accuracy_test.py
- ci/L0_backend_vllm/accuracy_test/test.sh
- ci/L0_backend_vllm/vllm_backend/test.sh
- samples/model_repository/vllm_model/1/model.json
Updated accuracy test not to run 2 vLLM engines at the same time, due to https://github.com/vllm-project/vllm/issues/2248
> Updating vLLM tests to handle changes between vLLM version 0.2.3 and 0.3.0

- ci/L0_backend_vllm/enabled_stream/enabled_stream_test.py
- ci/L0_backend_vllm/enabled_stream/test.sh
- ci/L0_backend_vllm/vllm_backend/test.sh
- ci/L0_backend_vllm/vllm_backend/vllm_backend_test.py
- ci/common/test_util.py
- samples/client.py
- src/model.py
This PR adds `exclude_input_in_output` flag to vllm backend inputs.
It only impacts non-streaming case.
For streaming case, I refactored code and return only `diffs`, e.g.:
Prompt = "The most dangerous animal is"
Response:
```
" the",
" one",
" that",
" is",
" most",
" likely",
" to",
" be",
" killed",
" by",
" a",
" car",
".",
```
The above case will be the only possible response in the streaming mode. Open to discussions.
cc @@mkhludnev
> Add `exclude_input_in_output` option to vllm backend

- src/model.py
Once the vLLM version is upgraded, we should add support this `min_tokens`. This will be used by Triton GenAi-Perf.
> Support min_tokens parameter

- ci/L0_multi_gpu/vllm_backend/test.sh
- ci/L0_multi_gpu/vllm_backend/vllm_multi_gpu_test.py
- src/model.py
When loading multiple instances of a vLLM model on a multi-gpu system (default behavior with KIND_GPU which is the default instance group when left unspecified), all model instances will default to the same device and can cause a CUDA OOM rather than loading a model on each GPU device assigned by the instance group settings.
This is rooted in Triton's KIND_GPU behavior making an assumption that the model is assigned only one GPU. In the future, KIND_GPU may be expanded to define a set of multiple GPUs for a single model. However, for now the recommendation is to use KIND_MODEL when a model can have multiple GPUs and use them freely (such as python models).
These changes try to account for this assumption by isolating the assigned GPU device ID when KIND_GPU is used, and otherwise raising …
> fix: Enhance checks around KIND_GPU and tensor parallelism

- ci/L0_multi_gpu/multi_lora/multi_lora_test.py
- ci/L0_multi_gpu/multi_lora/test.sh
explicit model load was causing failures in tests with vllm==v0.5.0.post1
> Removed explicit mode for multi-lora

- src/model.py
Address review comments for https://github.com/triton-inference-server/vllm_backend/pull/46
https://github.com/triton-inference-server/vllm_backend/pull/46
N/A
N/A
N/A
N/A
N/A
N/A
> fix: Address review comments

- ci/L0_multi_gpu/multi_lora/test.sh
- ci/L0_multi_gpu/vllm_backend/test.sh
- samples/model_repository/vllm_model/1/model.json
In PR [#5230](https://github.com/vllm-project/vllm/pull/5230) vllm changed default executor for distributed serving from Ray to `python native multiprocessing` for single node processing. This becomes in issue to Triton starting with v0.5.1 release.
For `python native multiprocessing` mode and KIND_MODEL setting, Triton hits "failed to stop server: Internal - Exit timeout expired. Exiting immediately." and `pt_main_thread` processes are never stopped/killed. I'll create an issue a bit later.
Solution: support only Ray for deploying models with tensor_parallel_size > 1 via "distributed_executor_backend" flag until the issue is fixed. 
This PR adjusts our multi-gpu tests according to the above observations
> test: Limiting multi-gpu tests to use Ray as distributed_executor_backend 

- src/model.py
Fix:
* Garbage collect when the request count drops to zero.
* Include garbage collect for non-streaming case.
* Fix improper placement of `decrement_ongoing_request_count = True`.
* Fix missing `lora_request` argument into `llm_engine.add_request()`.
for https://github.com/triton-inference-server/vllm_backend/pull/46 PR.
https://github.com/triton-inference-server/vllm_backend/pull/46
N/A
This PR is to fix some issues on the performance improvement https://github.com/triton-inference-server/vllm_backend/pull/46 PR, so any issues should be covered by existing tests.
- CI Pipeline ID: 16926866
N/A
N/A
N/A
N/A
> fix: Include garbage collect for non streaming and improve triggering logic

- src/model.py
Triton's output token throughput for generate endpoint increases by 18% for concurrency 50. There is still a small gap between vLLM-only and vLLM + Triton solution.
The model is llama-2-7b.
Changes:
* Use add_request instead of generate for vLLM backend. It appears that with generate , the token generation is delayed until the next iteration of the loop.
* Delegate response sending to a separate thread.
Next steps:
* In the long term it might be better to have an async_send API to avoid creating a separate thread for sending the responses.
N/A
N/A
This is a performance improvement, existing test cases should be sufficient at covering any …
> perf: Improve vLLM backend performance by using a separate thread for responses

- src/model.py
Remove the explicit calling to garbage collector. The lifecycle of response_sender and response_factory are expected to be handled by the Python backend internally.
https://github.com/triton-inference-server/server/pull/7504
https://github.com/triton-inference-server/python_backend/pull/373
N/A
The PR refactors how the response_sender object lifecycle is handled, it is neither a feature nor a bug fix, so existing tests should be sufficient to cover any regression.
- CI Pipeline ID: 17156719
When parallel tensors > 1, the stub process can fail to unload (with finalize() called and returned successfully), so it is necessary to manually call …
> refactor: Remove explicit callings to garbage collect

- src/model.py
Cancellation check is to be performed during the response loop on the response thread. The status of the cancellation will be written back a object shared between the response loop and generate loop on a particular request. After sending a response, the cancellation status will be checked and the generate loop will cancel the generation if the request is cancelled. Combined with the release of GIL while checking for cancellation, this maximizes the vLLM generation time on the GIL, which has seen noticeable performance improvement.
https://github.com/triton-inference-server/python_backend/pull/372
Start at once a cancellation is issued …
> perf: Check for cancellation on response thread

- README.md
- ci/L0_backend_vllm/metrics_test/vllm_metrics_test.py
- src/utils/metrics.py
Sample histogram output
```
vllm:time_to_first_token_seconds_count{model="vllm_opt",version="1"} 3
vllm:time_to_first_token_seconds_sum{model="vllm_opt",version="1"} 0.0002238750457763672
vllm:time_to_first_token_seconds_bucket{model="vllm_opt",version="1",le="0.001"} 3
vllm:time_to_first_token_seconds_bucket{model="vllm_opt",version="1",le="0.005"} 3
vllm:time_to_first_token_seconds_bucket{model="vllm_opt",version="1",le="0.01"} 3
vllm:time_to_first_token_seconds_bucket{model="vllm_opt",version="1",le="0.02"} 3
vllm:time_to_first_token_seconds_bucket{model="vllm_opt",version="1",le="0.04"} 3
vllm:time_to_first_token_seconds_bucket{model="vllm_opt",version="1",le="0.06"} 3
vllm:time_to_first_token_seconds_bucket{model="vllm_opt",version="1",le="0.08"} 3 …
```
> feat: Report histogram metrics to Triton metrics server

- README.md
- ci/L0_backend_vllm/metrics_test/vllm_metrics_test.py
- src/model.py
- src/utils/metrics.py
Report more histogram metrics from vLLM to Triton metrics server.
```
histogram_e2e_time_request
histogram_num_prompt_tokens_request
histogram_num_generation_tokens_request
histogram_best_of_request
histogram_n_request
```
n/a
n/a
ci/L0_backend_vllm/metrics_test
17681888
n/a
Customers requested additional histogram metrics from vLLM.
n/a
> feat: Report more histogram metrics

- ci/L0_backend_vllm/metrics_test/test.sh
- ci/L0_backend_vllm/metrics_test/vllm_metrics_test.py
Fix L0_backend_vllm jobs. The metric outputs varies on the platform with non-greedy sampling. Move the checks for sampling parameter related metrics into a separate test case.
Broken pipeline ID: 109056988
n/a
n/a
VLLMTritonMetricsTest.test_custom_sampling_params
18003888
n/a
n/a
n/a
> fix: Fix L0_backend_vllm* jobs

- src/model.py
- src/utils/metrics.py
Optimize vLLM by reporting metrics in a separate thread.
https://github.com/triton-inference-server/python_backend/pull/379
n/a
L0_backend_vllm/metrics_test
18506139
n/a
n/a
n/a
> perf: vLLM metrics optimization

- ci/L0_backend_vllm/enabled_stream/enabled_stream_test.py
- ci/L0_backend_vllm/test.sh
- ci/L0_multi_gpu/test.sh
1. Resolves local vs system package errors around `pip` installation in Ubuntu 24.04 tests by removing the `pip install --upgrade pip`. The pip upgrade shouldn't be necessary for any installations in these tests.
Example error before this change:
```bash
$ pip install --upgrade pip
Requirement already satisfied: pip in /usr/lib/python3/dist-packages (24.0)
Collecting pip
Using cached pip-24.3.1-py3-none-any.whl.metadata (3.7 kB)
Using cached pip-24.3.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
Attempting uninstall: pip
Found existing installation: pip 24.0
ERROR: Cannot uninstall pip 24.0, RECORD file not found. Hint: The package was installed by debian.
```
2. Replaces the [now-deprecated](https://docs.python.org/3/whatsnew/3.12.html#id3) unittest assertEquals with …
> fix: Remove unnecessary pip upgrades in testing

- ci/L0_backend_vllm/enabled_stream/enabled_stream_test.py
- ci/L0_backend_vllm/test.sh
- ci/L0_multi_gpu_vllm/test.sh
This PR is subset of changes which need to be carried over to the `main` branch after the release
> Update `main` branch post 24.11

- ci/L0_backend_vllm/metrics_test/test.sh
- src/model.py
It seems like we need to be careful, when using asyncio with multi-threading. The non-graceful shutdown was happening due to "RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one\n\nA" (I started `asyncio.run` with `debug=True`). Thus I'm replacing asyncio with threading.
Tests: https://gitlab-master.nvidia.com/dl/dgx/tritonserver/-/jobs/129814805
tests ran for branch `oandreeva_metrics_refactor`, but the change is the same. I suggest to merge this commit to the current perf PR and merge perf PR to main, i.e. not wait for metrics follow up.
> Setting shutdown asyncio event in a thread-safe manner

- samples/client.py
- `asyncio.get_event_loop()` was deprecated in Python 3.12.
- Initialize gRPC client inside the async loop.
More details in the Jira ticket.
L0_model_control_stress_valgrind_massif_vllm--base
L0_model_control_stress_valgrind_vllm--base
L0_model_control_stress_vllm--base
21774566
Pipeline job failures
- closes GitHub issue: #xxx
> ci: Fix L0_model_control_stress_vllm

- ci/L0_backend_vllm/accuracy_test/accuracy_test.py
- ci/L0_backend_vllm/accuracy_test/test.sh
- ci/L0_backend_vllm/metrics_test/vllm_metrics_test.py
- ci/L0_multi_gpu_vllm/multi_lora/test.sh
- src/model.py
- src/utils/vllm_backend_utils.py
This PR removes dependencies on `vllm.SamplingParams` names, present in `_get_sampling_params_dict` in favor of dynamically checking sampling parameters passed with the request with `vllm.SamplingParams.__annotations__`
Previously, we needed to keep track about SamplingParams members and their types: e.g. float keys as defined [here](https://github.com/triton-inference-server/vllm_backend/blob/d061556955b89d538ec53f32c532e2041ce2fc89/src/model.py#L716-L722). 
I suggest to infer the type from `vllm.SamplingParams.__annotations__` and for simple ones (int, float, bool, str, Optional[int]) perform a conversion from string to the expected type. Suggested logic is implemented [here](https://github.com/triton-inference-server/vllm_backend/compare/oandreeva_sampling_parameters?expand=1#diff-3453d …
> [fix] Sampling Parameters related improvements

- README.md
- ci/L0_backend_vllm/metrics_test/vllm_metrics_test.py
- src/model.py
- src/utils/metrics.py
Adjusting metrics-related codebase to work with some API changes in latest vllm.
Removing number check in metrics tests in favor of just checking that vllm - related metrics are populated on metrics endpoint.
[Edit 1] It seems like the metric calculation changed in versions 0.6.4+ and the upgrade was breaking our tests. In this PR for now I suggest to check that custom metrics were found among the metrics reported by Triton and avoid testing values. 
[Edit 2] What became broken prior to 0.6.4 release, custom metrics were reported in the test as:
```
curl localhost:8002/metrics | grep "vllm:request_params_n_bucket"
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 12703  100 12703    0     0  6202k      0 --:--:-- …
```
> [fix] Adjusting VllmStatLogger for 0.7.0 changes in API

- README.md
- ci/L0_backend_vllm/metrics_test/vllm_metrics_test.py
- src/model.py
- src/utils/metrics.py
Related to these two PRs:
* https://github.com/triton-inference-server/server/pull/7978
* https://github.com/triton-inference-server/vllm_backend/pull/81
> [fix] Adjusting VllmStatLogger for 0.7.0 changes in API (#81)

- ci/L0_multi_gpu_vllm/vllm_backend/vllm_multi_gpu_test.py
- src/model.py
in my experiments with loading multiple models onto different gpus `torch.cuda.set_device` wasn't behaving as a GPU "router", thus using CUDA_VISIBLE_DEVICES
before the fix, `tp=1 count=2` test GPU utilisation:
```
Test Matrix: model='vllm_opt_KIND_GPU_tp1_count2', kind='KIND_GPU', tp='1', instance_count='2'
=============== Before Loading vLLM Model ===============
GPU 0 Memory Utilization: 1426849792 bytes
GPU 1 Memory Utilization: 1426849792 bytes
=============== After Loading vLLM Model ===============
GPU 0 Memory Utilization: 44708986880 bytes
GPU 1 Memory Utilization: 1866727424 bytes
```
With this fix:
```
Test Matrix: model='vllm_opt_KIND_GPU_tp1_count2', kind='KIND_GPU', tp='1', instance_count='2'
=============== Before Loading vLLM Model ===============
GPU 0 Memory Utilization: …
```
> [fix] replacing torch.cuda.set_device with CUDA_VISIBLE_DEVICES

- ci/L0_backend_vllm/vllm_backend/test.sh
- ci/L0_multi_gpu_vllm/multi_lora/test.sh
- docs/llama_multi_lora_tutorial.md
- samples/model_repository/vllm_model/1/model.json
VLLM sets new config enable_log_requests: false by default.
See https://github.com/vllm-project/vllm/pull/21739
> ci: Remove deprecated vLLM config "disable_log_requests"

- ci/L0_additional_outputs_vllm/test.sh
- ci/L0_backend_vllm/test.sh
- ci/L0_check_health_vllm/test.sh
- ci/L0_multi_gpu_vllm/multi_lora/test.sh
- ci/L0_multi_gpu_vllm/test.sh
- ci/L0_multi_gpu_vllm/vllm_backend/test.sh
Default branch needst to be updated after 25.09 to include inroduced updates.
> TPRD-1710: Update default branches post-25.09
